import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";
import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { firebase } from "config";
import { AngularFireModule } from "@angular/fire"; //firebase core (required)
import { AngularFireAuthModule } from "@angular/fire/auth";
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { ErrorComponent } from './error/error.component'; //example of adding additional firebase products

@NgModule({
  declarations: [AppComponent, AutoGeneratedComponent, ErrorComponent],
  imports: [
    BrowserModule.withServerTransition({ appId: "serverApp" }),
    AppRoutingModule,
    BrowserAnimationsModule,
    AngularFireModule.initializeApp(firebase, "my-app-name"),
    AngularFireAuthModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
